# -*- coding: utf-8 -*-
"""simplecode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dbqDLMUIdcydyuFLq1d5ZlGslL-zsC2J
"""

#translate DNA to Protein
def dna_to_protein(dna_seq):
    """
    Translate a DNA sequence into a protein sequence.
    Input:
        dna_seq (str): DNA sequence composed of A, T, G, C.
    Output:
        str: Protein sequence (amino acids, single-letter code).
    """
    # Standard genetic code table
    codon_table = {
        'ATA':'I', 'ATC':'I', 'ATT':'I', 'ATG':'M',
        'ACA':'T', 'ACC':'T', 'ACG':'T', 'ACT':'T',
        'AAC':'N', 'AAT':'N', 'AAA':'K', 'AAG':'K',
        'AGC':'S', 'AGT':'S', 'AGA':'R', 'AGG':'R',
        'CTA':'L', 'CTC':'L', 'CTG':'L', 'CTT':'L',
        'CCA':'P', 'CCC':'P', 'CCG':'P', 'CCT':'P',
        'CAC':'H', 'CAT':'H', 'CAA':'Q', 'CAG':'Q',
        'CGA':'R', 'CGC':'R', 'CGG':'R', 'CGT':'R',
        'GTA':'V', 'GTC':'V', 'GTG':'V', 'GTT':'V',
        'GCA':'A', 'GCC':'A', 'GCG':'A', 'GCT':'A',
        'GAC':'D', 'GAT':'D', 'GAA':'E', 'GAG':'E',
        'GGA':'G', 'GGC':'G', 'GGG':'G', 'GGT':'G',
        'TCA':'S', 'TCC':'S', 'TCG':'S', 'TCT':'S',
        'TTC':'F', 'TTT':'F', 'TTA':'L', 'TTG':'L',
        'TAC':'Y', 'TAT':'Y', 'TAA':'_', 'TAG':'_',
        'TGC':'C', 'TGT':'C', 'TGA':'_', 'TGG':'W',
    }

    # Clean input
    dna_seq = dna_seq.upper().replace(" ", "")

    protein = ""
    # Translate in steps of 3 bases (codons)
    for i in range(0, len(dna_seq) - 2, 3):
        codon = dna_seq[i:i+3]
        protein += codon_table.get(codon, 'X')  # 'X' for unknown codon

    return protein

print(dna_to_protein("ATGGCCATTGTAATGGGCCGCTGAAAGGGTGCCCGATAG"))

#calculate Hamming distance
def hamming_distance(str1, str2):
    """
    Calculate the Hamming distance between two strings.
    If lengths differ, pad the shorter one with '-' to make them equal.
    """
    max_len = max(len(str1), len(str2))
    str1 = str1.ljust(max_len, '-')  # pad with '-'
    str2 = str2.ljust(max_len, '-')

    distance = sum(ch1 != ch2 for ch1, ch2 in zip(str1, str2))
    return distance

slack_username = "Khanh"
twitter_handle = "khanh0799"

dist = hamming_distance(slack_username, twitter_handle)
print(f"Hamming distance between '{slack_username}' and '{twitter_handle}' = {dist}")